
# auto-generated by configure
PREFIX = /home/ptbcsisi/laravel/node_modules/pngquant-bin/vendor
VERSION = 
CC = gcc
CFLAGS = -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I./lib -I/usr/include/libpng12    
LDFLAGS =  ./lib/libimagequant.a -lpng12   -lz   -lm
COCOA_READER = 0
SOLIBSUFFIX = so
STATICLIBDEPS = ./lib/libimagequant.h ./lib/libimagequant.a
LIQSRCDIR = ./lib
LIQCONFIGUREFLAGS = '--quiet' '--prefix=/home/ptbcsisi/laravel/node_modules/pngquant-bin/vendor' 

